### ISSUE TITLE
invalid code 

### ISSUE THREAD

**Issue by X-xTruex-X** [VRLabs/Avatars-3.0-Manager#16]
after I use vrlabs to add something to my avi it says this : StyleSheet import: type=Validation, code=InvalidProperty file=Assets/VRLabs/Avatars 3.0 Manager/Editor/Resources/AV3M/AV3ManagerStyle.uss:46
    Expected end of value but found '-1'

**Comment by Cibbi** [comment]
This warning doesn't cause any real issue to either the manager, your avatar, or the project. It's just unity acting dumb sometimes when it parses uss files.

Honestly i've been trying to find a way to avoid unity complaining in the first place, but it complains about values in the uss that then uses properly in the ui.

I'll check if unity continues giving this issue in future unity versions since sooner or later we're moving to Unity 2022
