### ISSUE TITLE
Allow installing into Unity Editor from git.

### ISSUE THREAD

**Issue by AraHaan** [VRLabs/Avatars-3.0-Manager#17]
Currently how the json is done is not friendly for the unity editor from git, as such a default version that is 'SemVer' compatible must be made for users who want to have an easier way of updating the manager itself without manually downloading and importing the updated copy manually. With this it would avoid imports as well since it could then be listed under ``packages``.

**Comment by Cibbi** [comment]
We won't make that change in the current repository structure due to how the main repository is managed currently, we don't want people to download broken commits. And it would need manual change of the file from our side, which is easy to forget and would rather find a way to automate it instead.

We are planning to change the repository structure, and that restructuring will support your request as well without the need for us to manually update the json over time.

I know it's annoying but please be patient. we're working on it.

Also, one note of advice: unless you specify the tag version for the download, the unity package manager will always download the latest commit, even if it isn't a new release but some in between (which could happen even with the new structure we're working on finalizing before applying it)

I'll keep this issue open so we can notify you when the new change is made and will work for your usecase

**Comment by Cibbi** [comment]
Reopening this since we're going through with changes in the package.json to allow this use case

**Comment by Cibbi** [comment]
As of recently we've made the changes in package.json that will allow you to install it from unity's package manager directly.

The version will always be pinned to the current minor release with a patch number of 999
