### ISSUE TITLE
Keep getting an error about Missing clipswapitem

### ISSUE THREAD

**Issue by XaleRokudo** [VRLabs/Avatars-3.0-Manager#9]
Here is the exact warning Assets\VRLabs\Avatars 3.0 Manager\Editor\Elements\ClipsSwapAreaElement.cs(15,22): error CS0246: The type or namespace name 'ClipSwapItem' could not be found (are you missing a using directive or an assembly reference?)

**Comment by Cibbi** [comment]
Delete the manager folder entirely and then reinstall the manager. Usualy that error happens when doing a 1.X to 2.X in place update of the manager.

For this kind of general issues, please come to https://discord.vrlabs.dev , there's a support forum where you can find some common issues already asnwered and if you have one that is new there's usually someone responding sooner than here. The github issues is more for development oriented people.
